### PR TITLE
Feature/webpack

### PR DESCRIPTION
**Pull request by vlkosinov**
What do you think? :blush:
#6

### CODE REVIEW

**Comment by gaearon** [comment]
Great! Let's use rimraf so it builds on Windows too?

**Comment by vlkosinov** [comment]
@gaearon done :+1:

**Comment by gaearon** [comment]
If we use babel we should also compile CommonJS to `lib` folder using Babel CLI and change `main` in package json to point to the compiled version.

**Comment by gaearon** [comment]
Thank you!

**Comment by tadjik1** [comment]
good job @vlkosinov !

**Comment by gaearon** [comment]
Thanks again! This got me to finally release 1.0 :-P

**Pull request merged**
