### PR TITLE
Use Lodash v4 and shortened paths

### PR DESCRIPTION
**Pull request by wbinnssmith**
Pros:

* New! Shiny! Hot off the presses lodash v4.0.0
* Likely longer maintained
* Shorter require paths

Cons:

* Bundled size goes from ~4.3k min+gz to 5.6kgz. ¯\\\_(ツ)\_/¯
* Drops support for IE < 9, like upcoming React v0.15

Tests continue to pass. Thanks Dan!

### CODE REVIEW

**Comment by gaearon** [comment]
Thanks! I'll leave this hanging for some time until v4 stabilizes and then merge.

**Comment by gaearon** [comment]
Gah, I decided to give it a go right away :D

**Comment by gaearon** [comment]
Out in 2.0.0.

**Comment by wbinnssmith** [comment]
:tada: :raised_hands:

**Pull request merged**
